version: '2'
services:
  app:
    image: spikerlabs/docker-magento2-app:latest
    ports:
      - 9000:9000
  server:
    image: spikerlabs/docker-magento2-server:latest
    ports:
      - 80:80
  database:
    image: mysql:5.7.16
    ports:
      - 3306:3306
  cache:
    image: redis:3.0.7
    ports:
      - 6379:6379
